appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: PLvu8Iazm2S0ntkTDcHjPZCn30NF/lFF/oVELdj8FnMT62FK+PMdKMWTvn+WTXYckkQW/IWrJ4jzmpIpG211JPunhVCDeQRdSfSoCusbbAIwvzTeGw06uglWq5tt02wGjty6J8Cmf5yjclSt39321zgMb1zb0GVh1Yvlkoi4B1PmZqbhLFECLjTztnjFQrI4Zi+f0ctIm1C6oXKgVtCtBW0IJCdetj3AX0ZY2dbWGJonllWPTUjiOvvkXGZ9FN9Fz5dsSxRKmHGoDjmF4BGtXyCIj9dymnKDLdO48CpJgqWGScmVm7rxxWWFLnXH6fVWTBlC0vQAazFF/Ogc+R0/WZnLNGPrMVax+bJWIBQ4BvM8WucNC7/+DPh8HmeNl5qlzVOALT9gA1W08bWwy5bTyUV6s/Fe9S9l5optroOa7dVVNeCoAwAkrLcPvbjMOBIWDmngBOUG6Hi7WDDTAt8DwkFETAFa2QfA+9YTqqvMfs733eiudf3B9sL8nkQT+wgunTG7uyMQQNN1H88OyywLznXrUXKbjt5rlVZe/ReIsTCfPANYFFkemf2zLjdbWYASj8bkhqeJnTmjePexptfk8DCJK6FsNvJnL1UI7MiV8y/8Arq9IJt4IYJeSTRJaUxJvS2FK2HsPgTdGBU0yCC1In/QyBxelXp8+lLxdrTlFdw=
conda_forge_output_validation: true
