travis:
  secure:
    BINSTAR_TOKEN: yJLGsfT8rN0qnlJqPEVK4kHTkjTjMKZ+qSzXMSY6JLz5O1owaAbu+mi9wTs/e4EXd4cqmvhe9zz9hpbjTAN8e5VR4TzZOG1MSEMnKJh7m7UkQpkgwqTtJ3fp29OVKDCcxMuTE+7eRBzKKVN8clQwmhFi/a3wneR5YsRL337qyq+UhHQuV16UeNKsUqkjmIu5T8C8xyBWF2+pZudxDCS3VC0EJekGF/GgC/lrnN8E8ATIpOsnzuPCv6QsrMAeujlrI8mXzChrvgDCB996LW7+bkTx9/zMeziqKWfWYK9wqKqSUF1nnLXV6/RQz9gL9SWMFbzbooi681SpdwD2x0z+fXk04r1BcUR2JA59n6YmdKAfP16WYPOLt64bRgfvtB+7ieeHTfVSFf6G7hv1T9QhSNJq0nGWGQ0PsWe0dVOiy3XUzHHGP0YqMrojQtOtQxLfSIfi9pRhb/qIQ+n9CPslrZXNyi8elbtV5sF7LvL7fMnwFVvUNpA/eYPvoYo9dt+2trzzXUenoBm3dsaI1kdMFbjuoSoni5nohSQ6PlguRcG4kmbtebb+VX1nYLqdEvvDPkaUXAUdmv/tgETtnsQidPC6ftDP0S+TCJzVbvZJ6fsxYKDqtnguQvPdsfvm1PyOdReVYR8qbhHY0R1B0gSONTHx2tjImDZ0nERjFYYIe7I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
